require_relative '../../sampleTS/node_modules/react-native/scripts/react_native_pods'
require_relative '../../sampleTS/node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def react_native_dependencies
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

def flipper_dependency
  # Note that using flipper requires use_frameworks! to be disabled.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'sampleTS' do
  react_native_dependencies

  target 'sampleTSTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'rn-sample-fixed-ios-lib' do
  react_native_dependencies
end

target 'rn-sample-fixed' do
  react_native_dependencies
  pod 'rn-sample-fixed-ios-lib', :path => "../../"
end
